data_root: image_data

data_read:
  train_dir: data/test_data/x_train
  test_dir: data/test_data/x_test
  index_separator: _
  image_id_index: 2
  label_index: 4

encoding_techniques:
  single_convolution: False
  double_convolution: False
  patch_convolution: True
  pseudo_differential_privacy: False
  pseudo_differential_privacy_patched: False
  differential_privacy: False
  differential_privacy_patched: False
  differential_privacy_single_convolution: False

save_encoding_images:
  enabled: True
  output_dir: data/encoded_data/



